version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - sudo yum update -y
      - sudo dnf module install nodejs:14
      - sudo yum install nodejs
      - npm install

  build:
    commands:
      - node server.js

artifacts:
  files:
    - "**/*"
  name: MyMegaApp-$(date +%Y-%m-%d) 
